name: Deploy to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  release:
    types: [published]
  push:
    branches:
      - style-2  # ONLY push to this branch will trigger preview deploy
    paths:
      - "data/**"
      - "pages/docs/**"

jobs:
  deploy:
    if: github.repository == 'CMPT-276-SPRING-2025/final-project-02-peaks'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Build project
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }}
          fi

      - name: Deploy to Vercel
        run: |
          OUTPUT=$(du --inodes -d 5 .vercel/output)
          echo "$OUTPUT"
          LAST=$(echo "$OUTPUT" | tail -n 1)
          PERCENTAGE=$(echo "$LAST" | awk 'BEGIN {maxtotal=15000} { printf "%.2f%%", ($1/maxtotal*100) }')
          echo "Vercel file usage percentage" >> $GITHUB_STEP_SUMMARY
          echo "$PERCENTAGE" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ github.event_name }}" == "release" ]]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
          fi

  load-data:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            data:
              - 'data/**'
      - name: Load JSON files
        if: steps.changes.outputs.data == 'true'
        run: curl -L -f https://biodrop.io/api/system/reload?secret=${{ secrets.BIODROP_API_SECRET }}
      - name: Load testimonials
        if: steps.changes.outputs.data == 'true'
        run: curl -L -f https://biodrop.io/api/system/testimonials-forms?secret=${{ secrets.BIODROP_API_SECRET }}
